# Generated by Django 4.2.3 on 2023-07-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='contact',
            field=models.CharField(max_length=30),
        ),
    ]
